apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api-deployment
  labels:
    app: dotnet-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
        - name: dotnet-api
          image: shweyasingh/nagp-app-shweta03:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
