apiVersion: v1
kind: Service
metadata:
  name: dotnet-api-service
  labels:
    app: dotnet-api
spec:
  type: LoadBalancer
  selector:
    app: dotnet-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
